version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - run-me

jobs:
  run-me:
    machine: true
    resource_class: trchopan/demo-server-1
    steps:
      - run:
          name: Clone the git repository
          command: git clone https://github.com/trchopan/demo-app.git -b $CIRCLE_BRANCH .
      - run:
          name: Check podman
          command: podman version
      - run:
          name: Build
          command: podman build . -t docker-registry.chop.dev:5000/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
      - run:
          name: Push to docker-registry 
          command: podman push docker-registry.chop.dev:5000/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
